### ISSUE TITLE
Ember: Testing Style

### ISSUE THREAD

**Issue by rwjblue** [DockYard/styleguides#10]
Add "Testing" section that covers the following:

- [ ] Unit Testing
- [ ] Integration Testing
- [ ] Acceptance Testing

Discuss what belongs in each, when should you use each, etc.

**Comment by michaeldupuisjr** [comment]
- [ ] How test helpers should be included (registering vs. ES6 modules)

**Comment by duggiefresh** [comment]
Closing in favor of MY new Testing Issue - https://github.com/DockYard/styleguides/issues/85

Sorry! 🍨
