### ISSUE TITLE
Whitespace in arrays

### ISSUE THREAD

**Issue by brzpegasus** [DockYard/styleguides#45]
Add something to the style guide about whitespace use in arrays:

```js
const foo = ['a', 'b', 'c'];
// vs.
const bar = [ 'a', 'b', 'c' ];
```

I thought we had decided on the first form, but I'm not seeing it documented.

**Comment by bcardarella** [comment]
Yes, prefer the first form.

**Comment by danmcclain** [comment]
+1 on the first form

**Comment by poteto** [comment]
We have a rule (side note: we need to fix links in the styleguide) for [single-line objects](https://github.com/dockyard/styleguides/blob/master/javascript.md#objects-1) where we pad it with a whitespace. Should we make them consistent?

**Comment by bcardarella** [comment]
I cannot explain why, but padded objects look OK to me but padded arrays do not.

**Comment by poteto** [comment]
I agree, but it might lead to something like this, which looks quite odd:

```js
export function foo([name, value]) {}
export function bar({ name, value }) {}
```

**Comment by danmcclain** [comment]
Like Brian, that actually looks fine to me

—

Dan

**Comment by poteto** [comment]
:ok_hand:
