### ISSUE TITLE
Style guide: Public Github repos

### ISSUE THREAD

**Issue by martndemus** [DockYard/styleguides#69]
Not sure if the style guide is the right place to put this.
I'd like to open discussion on having a standard template for public DockYard GH repos.

Things to think about:
- The footer of README.md, should we use the footer of [auth_test_support](https://github.com/DockYard/auth_test_support) as template.
- Should we add a CoC?
- Github now supports `ISSUE_TEMPLATE` and `PULL_REQUEST_TEMPLATE`, lets take advantage of those.

**Comment by bcardarella** [comment]
I've been copying/pasting from other projects but yes we should have a template. The fooler from auth_test_support is a good place to start.

I really like the ReactRouter project's ISSUE_TEMPLATE: https://github.com/reactjs/react-router/issues/new

**Comment by duggiefresh** [comment]
Currently a WIP - https://github.com/DockYard/styleguides/pull/70

**Comment by duggiefresh** [comment]
Closing since #70 has been merged. Please see https://github.com/DockYard/styleguides/tree/master/.github
