### ISSUE TITLE
Mandate the use of the `action` keyword when passing down an action.

### ISSUE THREAD

**Issue by martndemus** [DockYard/styleguides#74]
I would like to add to the style guide that people have to keep using the Closure Action keyword when passing on an action. In a lot of cases this is not necessary, but it is in a few edge cases.

The [Ember Guides](https://guides.emberjs.com/v2.4.0/components/triggering-changes-with-actions/#toc_calling-actions-up-multiple-component-layers) also does this in it's examples.

It also just makes it more obvious to your fellow engineers what is an action and what is a variable.

=================
The case i've found is that when you have a default action, then the context will not be set-up correctly.

```js
export default Component.extend({
  update(/*arguments */) {
    // do something with `this`
  }
});
```

```hbs
{{my-component update=update}}
```

If that action gets called the `this` context will not be what you expect and can cause bugs.

**Comment by danmcclain** [comment]
I am :+1: on this for sure, eliminate foot guns

**Comment by brzpegasus** [comment]
PR?

**Comment by courajs** [comment]
> It also just makes it more obvious to your fellow engineers what is an action and what is a variable.
:+1:
