### ISSUE TITLE
Elixir: Fix "bad" square example

### ISSUE THREAD

**Issue by SaladFork** [DockYard/styleguides#99]
In the [Whitespace](https://github.com/DockYard/styleguides/blob/master/engineering/elixir.md#whitespace) section, the following examples are shown:
```elixir
# bad
def square(a) when a > 0,
  do: a * a

# good
def square(a) when a > 0,
  do: a * a
```

These are the same, and should probably not be.

**Comment by bcardarella** [comment]
I spent way too long looking at those two examples before reading your last line. Agreed, looking into it.

**Comment by bcardarella** [comment]
Looking at it, I'm not entirely sure what the "bad" example is supposed to be. I guess we could write is more crappy?

**Comment by SaladFork** [comment]
Haha! I won't admit how long I stared at them before filing this issue...

The description above the examples states:
> Use two-space indentation and spaces around operators, after commas, colons and semicolons.

The `answer` example shows spaces around operators, the `Enum.map` example shows spaces after a comma. I think a good one for `square` would be to have it show spaces after colons:
```
# bad
def square(a) when a > 0,
  do:a * a

# good
def square(a) when a > 0,
  do: a * a
```

**Comment by bcardarella** [comment]
Is the first form even valid?

**Comment by SaladFork** [comment]
Nope.

```elixir
iex(1)> def square(a) when a > 0,
...(1)>   do:a * a
** (SyntaxError) iex:2: keyword argument must be followed by space after: do:
```
😐

**Comment by duggiefresh** [comment]
I think it should of been `a*a` - [I even had a PR for it](https://github.com/DockYard/styleguides/pull/84), but I can't recall why I closed it

**Comment by bcardarella** [comment]
OPEN IT! 🎅

**Comment by duggiefresh** [comment]
![](http://www.drchrisstephens.com/wp-content/uploads/2010/10/teamwork-sign1.jpg)
